export default {
  doNewSubGlow: true,
  doAnniversaryGlow: true,
  showYears: true,
  showPaidUpgrades: false,
  animatedEmotes: false,
  showBitValues: false,
  showCheerTotalValue: true,
  animatedCheermotes: false,
  showGameTitle: true,
  showStreamTitle: true,
  showStreamLength: true,
  showRoomstateToasts: true,
  showRaidmodeToasts: true,
  doGradiant: true,
  defaultSlow: 30,
  defaultFollowers: 10,
  toastDuration: 5000,
};
