export default {
  _id: "620a205907fba6ea52b4089a",
  payload: {
    userstate: {
      "badge-info": { subscriber: "0" },
      badges: { subscriber: "0" },
      color: null,
      "display-name": "KayaDox",
      emotes: null,
      flags: null,
      id: "4ebdbc0e-2d6a-4908-8e83-454a89752150",
      login: "kayadox",
      mod: false,
      "msg-id": "sub",
      "msg-param-cumulative-months": true,
      "msg-param-months": false,
      "msg-param-multimonth-duration": true,
      "msg-param-multimonth-tenure": false,
      "msg-param-should-share-streak": false,
      "msg-param-sub-plan-name": "Armory Enlistment",
      "msg-param-sub-plan": "1000",
      "msg-param-was-gifted": "false",
      "room-id": "51533859",
      subscriber: true,
      "system-msg": "KayaDox subscribed at Tier 1.",
      "tmi-sent-ts": "1644830809102",
      "user-id": "554113084",
      "user-type": null,
      "emotes-raw": null,
      "badge-info-raw": "subscriber/0",
      "badges-raw": "subscriber/0",
      "message-type": "sub",
    },
  },
  cleared: true,
  createdAt: "2022-02-14T09:26:49.102Z",
  __v: 0,
};
