name: Deploy to Digital Ocean

on:
  push:
    branches: [ main ]

env:
  REGISTRY: "registry.digitalocean.com/dbkynd"
  IMAGE_NAME: "stream-info2"

jobs:
  build_push_pull_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Build Image
        uses: docker/build-push-action@v5
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max

      #- name: Install doctl
      #  uses: digitalocean/action-doctl@v2
      #  with:
      #    token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      #- name: Log in to DigitalOcean Container Registry with short-lived credentials
      #  run: doctl registry login --expiry-seconds 600

      #- name: Push new image
      #  run: docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME):latest
